version: '3.7'
services:

  mysql:
    container_name: db
    build:
      dockerfile: ./Dockerfile.DB
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: plus
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - app_network

  migration:
    image: imega/mysql-client
    command: sh -c "mysql --host=mysql --user=root --password=test --database=plus <\"plus/install/manual installation/database/mysql_new_install.txt\""
    working_dir: /var
    volumes:
      - ./:/var/
    networks:
      - app_network

  vulnerable_app:
    container_name: backend
    build:
      dockerfile: ./Dockerfile.BACKEND
    restart: always
    depends_on:
      - mysql
    working_dir: /var/www/html
    volumes:
      - .:/home
    ports:
     - 80:80
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
