ALTER DATABASE %1$s DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci;

ALTER TABLE bot_bot CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE bot_bots CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE bot_conversationlog CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE bot_dstore CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE bot_gmcache CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE bot_gossip CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE bot_patterns CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE bot_templates CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE bot_thatindex CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE bot_thatstack CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE %4$s CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE %5$s CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE %6$s CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE %7$s CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE %8$s CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE %9$s CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE %10$s CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;